name: Bug
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What is happening? Include error messages or unexpected output.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should happen instead?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal config or commands to trigger the bug.
  - type: textarea
    id: fix
    attributes:
      label: Suggested fix
      description: If you have an idea for how to fix this.
