name: Chore
description: Maintenance, refactoring, or infrastructure work
labels: ["type/chore"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What needs to be done?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this worth doing?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Relevant files, prior discussions, or related issues.
