name: Feature
description: Request a new feature or resource type
labels: ["type/feature"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Brief description of the feature.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this needed? What problem does it solve?
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Suggested config
      description: Example YAML configuration (if applicable).
      render: yaml
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Implementation considerations, edge cases, or constraints.
